# Generated by Django 3.1.12 on 2021-07-01 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=300)),
                ('code', models.CharField(default=None, max_length=300)),
                ('view_type', models.CharField(choices=[('list', 'list'), ('select', 'select')], default='list', max_length=400)),
                ('type', models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('boolean', 'boolean'), ('option', 'option'), ('multi_option', 'multi option')], default='text', max_length=100)),
                ('filter_type', models.CharField(blank=True, choices=[('multiple', 'multiple'), ('option', 'option'), ('boolean', 'boolean'), ('range', 'range')], default=None, max_length=100, null=True)),
                ('use_filter', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeOptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default=None, max_length=400)),
                ('code', models.CharField(default=None, max_length=400)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
            ],
        ),
    ]
