# Generated by Django 3.0.8 on 2020-10-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('imgurl', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('size', models.CharField(default='', max_length=300)),
                ('h_in', models.CharField(default='', max_length=300)),
                ('h_out', models.CharField(default='', max_length=300)),
                ('eksterier', models.CharField(default='', max_length=300)),
                ('interier', models.CharField(default='', max_length=300)),
                ('doors', models.CharField(default='', max_length=300)),
                ('floor', models.CharField(default='', max_length=300)),
                ('electrik', models.CharField(default='', max_length=300)),
                ('imgurl', models.ImageField(blank=True, null=True, upload_to='static/images/products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
