# Generated by Django 3.0.8 on 2020-10-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201002_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imgurl',
        ),
        migrations.CreateModel(
            name='Itemimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.ImageField(blank=True, null=True, upload_to='static/images/products')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
            ],
        ),
    ]
