# Generated by Django 3.1.3 on 2021-03-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201005_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='doors_en',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='doors_ru',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='doors_uk',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='eksterier_en',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='eksterier_ru',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='eksterier_uk',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='electrik_en',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='electrik_ru',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='electrik_uk',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='floor_en',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='floor_ru',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='floor_uk',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='interier_en',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='interier_ru',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='interier_uk',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_en',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_ru',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_uk',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
