# Generated by Django 3.1.3 on 2021-03-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210301_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ge',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='doors_ge',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='eksterier_ge',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='electrik_ge',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='floor_ge',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='interier_ge',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_ge',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
