# Generated by Django 3.0.7 on 2021-05-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210512_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('name_en', models.CharField(default='', max_length=300, null=True)),
                ('name_uk', models.CharField(default='', max_length=300, null=True)),
                ('name_ge', models.CharField(default='', max_length=300, null=True)),
                ('name_ru', models.CharField(default='', max_length=300, null=True)),
                ('name_tr', models.CharField(default='', max_length=300, null=True)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(blank=True, default=None, null=True)),
                ('category', models.ManyToManyField(to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.ImageField(blank=True, null=True, upload_to='static/images/products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Itemimage',
        ),
    ]
