# Generated by Django 3.0.7 on 2021-05-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_pr_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pr_type',
            new_name='type',
        ),
    ]
