# Generated by Django 3.0.7 on 2021-05-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210522_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=300)),
                ('code', models.CharField(default=models.CharField(default=None, max_length=300), max_length=300)),
                ('type', models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('bool', 'bool')], default='text', max_length=100)),
            ],
        ),
    ]
