# Generated by Django 3.0.7 on 2021-05-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210522_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('boolean', 'boolean')], default='text', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('integer', models.IntegerField(blank=True, default=None, null=True)),
                ('boolean', models.BooleanField()),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
