# Generated by Django 3.0.7 on 2021-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210522_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='filter_type',
            field=models.CharField(choices=[('multiple', 'multiple'), ('option', 'option')], default='multiple', max_length=100),
        ),
    ]
