# Generated by Django 3.0.7 on 2021-05-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productattribute_user_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='user_filter',
            new_name='use_filter',
        ),
    ]
