# Generated by Django 3.0.7 on 2021-05-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210524_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='boolean',
            field=models.CharField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, max_length=20, null=True),
        ),
    ]
