# Generated by Django 3.0.7 on 2021-05-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210524_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='code',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='boolean',
            field=models.CharField(blank=True, choices=[('true', 'Yes'), ('false', 'No')], default=None, max_length=20, null=True),
        ),
    ]
