# Generated by Django 3.0.7 on 2021-05-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_productattributevalue_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='code',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
