# Generated by Django 3.1.12 on 2021-06-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_attributeoption_attributeoptiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='option_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.attributeoptiongroup'),
        ),
    ]
