# Generated by Django 3.1.12 on 2021-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productattribute_option_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('multiple', 'multiple'), ('option', 'option')], default='multiple', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('boolean', 'boolean'), ('option', 'option'), ('multi_option', 'multi option')], default='text', max_length=100),
        ),
    ]
