# Generated by Django 3.1.12 on 2021-06-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210604_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('multiple', 'multiple'), ('option', 'option')], default=None, max_length=100, null=True),
        ),
    ]
