# Generated by Django 3.1.12 on 2021-06-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210604_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
