# Generated by Django 3.1.12 on 2021-06-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20210604_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('boolean', 'boolean'), ('option', 'option'), ('multi_option', 'multi option')], default='text', max_length=100),
        ),
    ]
