# Generated by Django 3.1.12 on 2021-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20210604_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='view_type',
            field=models.CharField(choices=[('list', 'list'), ('select', 'select')], default='list', max_length=400),
        ),
    ]
