# Generated by Django 3.1.12 on 2021-06-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_productattribute_view_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('multiple', 'multiple'), ('option', 'option'), ('boolean', 'boolean')], default=None, max_length=100, null=True),
        ),
    ]
