# Generated by Django 3.1.12 on 2021-06-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20210620_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='code',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
