# Generated by Django 3.1.12 on 2021-06-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210620_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('multiple', 'multiple'), ('option', 'option'), ('boolean', 'boolean'), ('range', 'range')], default=None, max_length=100, null=True),
        ),
    ]
