# Generated by Django 3.1.12 on 2021-06-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20210630_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
