# Generated by Django 3.1.12 on 2021-06-30 19:22

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20210630_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='static/images/category_images', verbose_name='Image'),
        ),
    ]
