# Generated by Django 3.1.12 on 2021-06-30 19:24

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_auto_20210630_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
