# Generated by Django 3.1.12 on 2021-06-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20210630_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmedia',
            old_name='ppio',
            new_name='ppoi',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
