# Generated by Django 3.1.12 on 2021-07-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20210630_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeoption',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='AttributeOptionGroup',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_multi_option',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_option',
        ),
        migrations.DeleteModel(
            name='AttributeOption',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
